#!/bin/bash
echo "Creating Game ID # 1"
echo ""
curl -X POST http://localhost:8000/game -d game_id=1
echo ""
echo "Fetching Game ID # 1"
echo ""
curl -X GET "http://localhost:8000/game?game_id=1"
echo ""
echo "Checking valid shape data against Game #1"
echo ""
curl -H "Content-Type: application/octet-stream" -X POST -d @shapedata.json "http://localhost:8000/shape?game_id=1" 
echo ""
echo "Checking INVALID shape data against Game #1"
echo ""
curl -H "Content-Type: application/octet-stream" -X POST -d @invalid_shapedata.json "http://localhost:8000/shape?game_id=1" 
echo ""
echo "Placing Valid shape into Game #1"
echo ""
curl -H "Content-Type: application/octet-stream" -X PUT -d @shapedata.json "http://localhost:8000/shape?game_id=1" 
echo ""
echo "Show me the placed shape..."
echo ""
curl -X GET "http://localhost:8000/game?game_id=1" 
echo "" 
echo "Checking formerly valid shape data against Game #1"
echo ""
curl -H "Content-Type: application/octet-stream" -X POST -d @shapedata.json "http://localhost:8000/shape?game_id=1" 
echo ""
echo "Attempting to place shape into Game #1 over another shape"
echo ""
curl -H "Content-Type: application/octet-stream" -X PUT -d @shapedata.json "http://localhost:8000/shape?game_id=1" 
echo ""
echo "Attempting to complete a line, then 'tick'"
curl -H "Content-Type: application/octet-stream" -X PUT -d @complete_line.json "http://localhost:8000/shape?game_id=1"
echo "Placed shape, now calling 'tick'"
curl -H "Content-Type: application/octet-stream" "http://localhost:8000/tick?game_id=1"
echo "done"
